
pipeline {
    agent { node { label 'Agent-1' } }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Init') { 
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                 terraform init
                '''
            }
        }
        stage('Plan') { 
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                 terraform plan
                '''
            }
        }
        stage('Approve') { 
            steps {
             input "Shall i apply?"
            }
        }
        stage('Apply') { 
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                 terraform apply -auto-approve
                '''
            }
        }
        stage('Destroy') { 
            steps {
             input "Shall i destroy?"
             sh '''
                cd 01-vpc
                ls -ltr
                pwd
                 terraform destroy -auto-approve
                '''
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}